/**
 * AIHub — 数据源
 * 来自 aihub-stations-urls.txt，350+ 条目收敛为 14 个编辑式分类。
 * 已剔除标注「已失效」的条目。每条配一句克制描述。
 * 两个版本共用同一份数据。
 */
window.AIHUB_DATA = {
  meta: {
    totalCategories: 4,
    updated: "2026-06-27",
  },
  categories: [
    {
      id: "relay",
      index: "01",
      name: "API 中转站",
      en: "Relay & Aggregators",
      kicker: "聚合与代理",
      desc: "为开发者提供官方模型的统一入口、价格优化与稳定调度。",
      items: [
        { name: "APIKEY.FUN", url: "https://apikey.fun", note: "官方原价 7 折，企业级高可用", tier: "企业" },
        { name: "星链 4SAPI", url: "https://4sapi.com", note: "480+ 模型，99.99% SLA", tier: "企业" },
        { name: "CatRouter", url: "https://catrouter.net", note: "500+ 模型，负载均衡，可开票", tier: "企业" },
        { name: "TokenRiver", url: "https://tokenriver.ai", note: "流式输出优化，零故障记录", tier: "企业" },
        { name: "ZenMux", url: "https://zenmux.ai", note: "仅官方授权渠道，原版模型", tier: "企业" },
        { name: "laozhang.ai", url: "https://laozhang.ai", note: "官方汇率，赠金，极简操作", tier: "企业" },
        { name: "AIHubMix", url: "https://aihubmix.com", note: "东京节点，完整缓存支持", tier: "企业" },
        { name: "诗云 API", url: "https://shiyunapi.com", note: "低至 5 折，金融政务合规", tier: "企业" },
        { name: "poloapi", url: "https://poloapi.com", note: "官方 93 折，非逆向", tier: "企业" },
        { name: "Leits API", url: "https://leitsapi.com", note: "企业级多数据中心", tier: "企业" },
        { name: "灵眸 AI", url: "https://api.lmuai.com", note: "¥2.4/$ 最低汇率，Claude Code 缓存", tier: "高性价比" },
        { name: "神马中转 API", url: "https://api.whatai.cc", note: "¥2/$，650+ 模型", tier: "高性价比" },
        { name: "PackyAPI", url: "https://www.packyapi.com", note: "¥1/$ 低价王，社区活跃", tier: "高性价比" },
        { name: "Right Code", url: "https://right.codes", note: "¥0.3/$，Claude Code 优化", tier: "高性价比" },
        { name: "极连 AI", url: "https://zovelox.com", note: "Opus 仅原价 7%，自研调度", tier: "高性价比" },
        { name: "CCGPAI", url: "https://ccgpai.com", note: "赠 $5，0.3 倍率", tier: "高性价比" },
        { name: "AI Code Mirror", url: "https://aicodemirror.com", note: "老牌，官方 3.8 折", tier: "高性价比" },
        { name: "apiyi", url: "https://apiyi.com", note: "运营稳定，部分缓存", tier: "高性价比" },
        { name: "Terminal.Pub", url: "https://terminal.pub", note: "按量 + 月订阅双模式", tier: "高性价比" },
        { name: "NiceCode", url: "https://nicecode.cc", note: "V2EX 多次推荐", tier: "社区" },
        { name: "DDS Hub", url: "https://ddshub.cc", note: "Claude Max 号池", tier: "社区" },
        { name: "DuckCoding", url: "https://duckcoding.com", note: "编码首选，口碑好", tier: "社区" },
        { name: "88code", url: "https://www.88code.org", note: "每天送 20+8 刀免费额度", tier: "社区" },
        { name: "aicoding.sh", url: "https://aicoding.sh", note: "大厂背景，稳定", tier: "社区" },
        { name: "AnyRouter", url: "https://anyrouter.top", note: "注册送 $125，LinuxDO/edu", tier: "公益" },
        { name: "GoGoGo 公益站", url: "https://api.chengtx.vip", note: "免费 Claude API", tier: "公益" },
        { name: "OpenRouter", url: "https://openrouter.ai", note: "全球最大 LLM 聚合，500 万+ 用户", tier: "国际" },
        { name: "302.AI", url: "https://302.ai", note: "全球聚合，15+ 厂商", tier: "国际" },
      ],
    },
    {
      id: "official",
      index: "02",
      name: "官方模型平台",
      en: "Official Models",
      kicker: "对话与云 API",
      desc: "来自一线实验室的旗舰模型，官方对话入口与免费额度。",
      items: [
        { name: "Claude", url: "https://claude.ai", note: "Anthropic 官方对话" },
        { name: "ChatGPT", url: "https://chat.openai.com", note: "OpenAI 官方" },
        { name: "Gemini", url: "https://gemini.google.com", note: "Google 官方" },
        { name: "Grok", url: "https://grok.com", note: "xAI 官方" },
        { name: "DeepSeek", url: "https://www.deepseek.com", note: "国产开源推理" },
        { name: "KIMI", url: "https://kimi.moonshot.cn", note: "月之暗面长上下文" },
        { name: "通义千问", url: "https://tongyi.aliyun.com", note: "阿里" },
        { name: "豆包", url: "https://www.doubao.com", note: "字节跳动" },
        { name: "文心一言", url: "https://yiyan.baidu.com", note: "百度" },
        { name: "Perplexity", url: "https://www.perplexity.ai", note: "AI 答案引擎" },
        { name: "Poe", url: "https://poe.com", note: "Quora 多模型聚合" },
        { name: "硅基流动", url: "https://siliconflow.cn", note: "国产推理加速，28ms 首 Token" },
        { name: "智谱 AI", url: "https://open.bigmodel.cn", note: "GLM 官方，GLM-4-Flash 免费" },
        { name: "DeepSeek API", url: "https://platform.deepseek.com", note: "官方 API，赠 10 元" },
        { name: "Moonshot API", url: "https://platform.moonshot.cn", note: "Kimi 官方，赠 15 元" },
        { name: "阿里云百炼", url: "https://bailian.aliyun.com", note: "阿里生态" },
        { name: "七牛云 AI", url: "https://api.qnaigc.com", note: "300 万 Token 免费，双协议" },
      ],
    },
    {
      id: "code",
      index: "03",
      name: "AI 编程",
      en: "Code Assistants",
      kicker: "编辑器与 Agent",
      desc: "从补全到自主工程，重塑日常写代码的方式。",
      items: [
        { name: "Cursor", url: "https://cursor.com", note: "AI 原生编辑器" },
        { name: "GitHub Copilot", url: "https://github.com/features/copilot", note: "企业标准" },
        { name: "Windsurf", url: "https://codeium.com", note: "免费替代，Codeium" },
        { name: "Replit", url: "https://replit.com", note: "浏览器 IDE" },
        { name: "v0", url: "https://v0.dev", note: "Vercel，设计转代码" },
        { name: "Bolt", url: "https://bolt.new", note: "全栈 AI 生成" },
        { name: "Lovable", url: "https://lovable.dev", note: "AI 全栈应用" },
        { name: "Trae", url: "https://www.trae.ai", note: "字节 AI 编程" },
        { name: "Aider", url: "https://www.aider.chat", note: "终端 AI 编程" },
        { name: "Cline", url: "https://cline.bot", note: "VS Code AI Agent" },
        { name: "Continue", url: "https://continue.dev", note: "开源 IDE AI" },
        { name: "Devin", url: "https://www.cognition.ai", note: "全自主 AI 工程师" },
        { name: "Sourcegraph Cody", url: "https://sourcegraph.com", note: "代码搜索 + AI" },
        { name: "Tabnine", url: "https://www.tabnine.com", note: "隐私优先" },
      ],
    },
    {
      id: "image",
      index: "04",
      name: "图像生成",
      en: "Image",
      kicker: "视觉创作",
      desc: "把文字变成画面，从摄影写实到矢量插画。",
      items: [
        { name: "Midjourney", url: "https://www.midjourney.com", note: "最佳 AI 美学" },
        { name: "DALL·E 3", url: "https://openai.com/dall-e", note: "OpenAI" },
        { name: "Stable Diffusion", url: "https://stability.ai", note: "开源基石" },
        { name: "Adobe Firefly", url: "https://www.adobe.com/firefly", note: "商业安全" },
        { name: "Ideogram", url: "https://ideogram.ai", note: "文字渲染最佳" },
        { name: "Leonardo", url: "https://leonardo.ai", note: "游戏资产" },
        { name: "Recraft", url: "https://www.recraft.ai", note: "矢量设计" },
        { name: "Krea AI", url: "https://krea.ai", note: "实时生成" },
        { name: "Lexica", url: "https://lexica.art", note: "SD 搜索引擎" },
        { name: "Civitai", url: "https://civitai.com", note: "模型社区" },
        { name: "LiblibAI", url: "https://www.liblib.art", note: "国内模型社区" },
        { name: "SeaArt", url: "https://seaart.ai", note: "亚洲审美" },
        { name: "TensorArt", url: "https://tensor.art", note: "中国 AI 图像平台" },
        { name: "GetImg", url: "https://getimg.ai", note: "AI 图像套件" },
      ],
    },
  ],
};
